Setup of documentation
qurit/PyTheranostics pull request #48
Opened 2024-05-26 22:47 UTC by carluri

- A documentation page has been setup in readthedocs. 
- The domain has been updated to reflect a qurit.ca repository.
- The package has been made available on PYPI so that installation documentation could be added.
- Requirements for the correct build of the documentation have also been included by splitting the requirements for the package from the requirements of the docs.

2024-05-26 22:49 UTC, carluri commented
@plesqui when you review you can close issue #37

2024-05-29 15:00 UTC, plesqui requested changes

2024-05-29 15:00 UTC, plesqui commented on .github/workflows/sphinx.yml
> +      - documentation
How does this work? Will we always have a documentation branch that we need to maintain, or can we just change this to our dev or main branch so that documentation build gets triggered when PRs happen there?

2024-05-29 15:00 UTC, plesqui commented on doodle/docs/source/API/modules.rst
On the built documentation, I only see functions. I don't see any documentation for any of the classes. Is this expected?

2024-05-29 15:00 UTC, plesqui commented on doodle/docs/source/_static/dosimetry_workflow.png
This is nice. I am thinking we should edit this image as currently pyTheranostics does only the purple box. Maybe add a bigger box around the purple indicating that's pyTheranostics support?

2024-05-29 15:00 UTC, plesqui commented on doodle/docs/source/conf.py
> +release = '0.3'
We will have to match this with actual release version once that happens.

2024-05-29 15:00 UTC, plesqui commented on doodle/docs/source/intro/overview.rst
> +PyTheranostics is a library of tools to process nuclear medicine scans and take them through the dosimetry workflow to calculate the absorbed dose in target organs. The library is designed to be modu
I would add "... process nuclear medicine scans **with organ and lesion segmentation masks** and take them through ..."

2024-05-29 15:00 UTC, plesqui commented on doodle/qc/dosecal_qc.py
This does not seem related to documentation. Are you sure it should be part of this PR?

2024-05-29 15:00 UTC, plesqui commented on doodle/qc/spect_qc.py
This does not seem to be related to documentation. Are you sure it is part of this PR?

2024-05-29 15:00 UTC, plesqui commented on requirements.txt
We might want to re-visit this and pin some versions.

2024-05-29 15:00 UTC, plesqui commented on setup.py
> +          'numpy','matplotlib','pandas','pydicom','openpyxl','rt-utils','scikit-image', 'simpleitk'
Any reason why we are more flexible with pandas version? I just want to confirm this is intended.

2024-05-29 15:10 UTC, carluri commented on .github/workflows/sphinx.yml
> +      - documentation
We can actually delete this file. Is not needed as readthedocs will keep track and automates it.

2024-05-29 15:17 UTC, carluri commented on doodle/docs/source/API/modules.rst
We will keep using ::autoclass:: as we move forward with this

2024-05-29 15:25 UTC, plesqui approved these changes

2024-05-29 15:26 UTC, merged