Sara preclinical dosimetry
qurit/PyTheranostics pull request #54
Opened 2024-11-28 00:42 UTC by sarakurkowska

Add lesion dosimetry methods

2024-12-30 23:53 UTC, plesqui requested changes

2024-12-30 23:53 UTC, plesqui commented on doodle/ImagingDS/LongStudy.py
> +        print(self._valid_masks)
Please remove print statement.

2024-12-30 23:53 UTC, plesqui commented on doodle/ImagingDS/LongStudy.py
> +        return numpy.sum(self.masks[time_id][region] * self.array_at(time_id=time_id) * self.voxel_volume(time_id=time_id)) / (numpy.sum(self.masks[time_id][region]) * self.voxel_volume(time_id=time_
I recommend simplifying this method using `numpy.mean`. In addition, if you want this method to only work for CT (and therefore ensuring that the returned value is in HU), I recommend adding an assertion:

```python
if self.modality != "CT": 
    raise AssertionError("Modality is not CT")
```

2024-12-30 23:53 UTC, plesqui commented on doodle/dosimetry/BaseDosimetry.py
> +
Ass discussed, please move this table to `data/s-values/tumors.csv`

2024-12-30 23:53 UTC, plesqui commented on doodle/dosimetry/OrganSDosimetry.py
> +    def composition_and_density_from_HU(self, density):
Please add types in your methods definitions: 

```python
def composition_and_density_from_HU(self, density: float) -> Tuple[str, float]:
```

etc

2024-12-30 23:53 UTC, plesqui commented on doodle/dosimetry/OrganSDosimetry.py
> +            df["TIA_h"] *
Please add units next to each quantity as comments (for clarity)

e.g., 
```python
df["TIA_h"] *  # MBq h
...
```

2025-01-09 00:00 UTC, sarakurkowska commented on doodle/dosimetry/BaseDosimetry.py
> +
done!

2025-01-09 00:02 UTC, sarakurkowska commented on doodle/dosimetry/OrganSDosimetry.py
> +    def composition_and_density_from_HU(self, density):
done!

2025-01-09 00:05 UTC, sarakurkowska commented on doodle/dosimetry/OrganSDosimetry.py
> +            df["TIA_h"] *
done

2025-01-09 00:14 UTC, sarakurkowska commented
I updated the code based on suggested changes

2025-01-22 16:26 UTC, plesqui approved these changes

2025-01-22 16:27 UTC, merged